// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package me.shy.netty.netty.rpc.grpc.userGen;

public interface UserNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.shy.demo.grpc.UserName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
