server:
  port: 8080

# 开启 Actuator，为了实现自动刷新
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      # 默认是 /actuator 前缀，这里修改为 /
      base-path: /
      exposure:
        include:
        # 暴露所有的接口
        # - "*"
        # 这里为了实现配置的自动刷新，只需要用到 /refresh 接口
        - "refresh"

data:
  env: NA
  user:
    username: NA
    password: NA
