###
# Date        : 2020-11-11 21:34:49
# Author      : shy
# Email       : yushuibo@ebupt.com / hengchen2005@gmail.com
# Version     : v1.0
# Description : -
###
server:
  port: 8103

spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  # 定义路由转发
  routes:
    # /api-a 开头的请求转发给 service-ribbon 服务处理
    api-a:
      path: /api-a/**
      service-id: service-ribbon
    # /api-b 开头的请求转发给 service-feign 服务处理
    api-b:
      path: /api-b/**
      service-id: service-feign

