// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package me.shy.demo.netty.rpc.grpc.greetingGen;

public interface GreetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.shy.demo.grpc.GreetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
