// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package me.shy.demo.netty.rpc.grpc.greetingGen;

public interface GreetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.shy.demo.grpc.GreetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greetWords = 1;</code>
   * @return The greetWords.
   */
  java.lang.String getGreetWords();
  /**
   * <code>string greetWords = 1;</code>
   * @return The bytes for greetWords.
   */
  com.google.protobuf.ByteString
      getGreetWordsBytes();
}
