// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package me.shy.demo.netty.rpc.grpc.userGen;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.shy.demo.grpc.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .me.shy.demo.grpc.User user = 1;</code>
   */
  java.util.List<me.shy.demo.netty.rpc.grpc.userGen.User> 
      getUserList();
  /**
   * <code>repeated .me.shy.demo.grpc.User user = 1;</code>
   */
  me.shy.demo.netty.rpc.grpc.userGen.User getUser(int index);
  /**
   * <code>repeated .me.shy.demo.grpc.User user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .me.shy.demo.grpc.User user = 1;</code>
   */
  java.util.List<? extends me.shy.demo.netty.rpc.grpc.userGen.UserOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .me.shy.demo.grpc.User user = 1;</code>
   */
  me.shy.demo.netty.rpc.grpc.userGen.UserOrBuilder getUserOrBuilder(
      int index);
}
