// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package me.shy.demo.netty.rpc.grpc.userGen;

public interface WordsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.shy.demo.grpc.Words)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string what_say = 1;</code>
   * @return The whatSay.
   */
  java.lang.String getWhatSay();
  /**
   * <code>string what_say = 1;</code>
   * @return The bytes for whatSay.
   */
  com.google.protobuf.ByteString
      getWhatSayBytes();
}
