###
# Date        : 2020-11-10 16:14:43
# Author      : shy
# Email       : yushuibo@ebupt.com / hengchen2005@gmail.com
# Version     : v1.0
# Description : -
###

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-feign

server:
  port: 8102

# 开启 feign 的 hytrix 支持
feign:
  hystrix:
    enabled: true
