logging:
  pattern:
    console: \%m\%n
  level:
    root: debug

spring:
  main:
    banner-mode: off
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://minikube:3306/demo?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: demo
    password: 123456
  kafka:
    template:
      default-topic: ods-base-log
    producer:
      acks: 0
    bootstrap-servers:
    - minikube:9092
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis-plus:
  global-config:
    db-config:
      field-strategy: not-null

mocker:
  mocker-concurrence: 10
  business-date: 2020-12-18
  collect-type: LOG
  is-clear: false
  user-clear: false
  new-user-count: 0
  male-user-rate: 20
  user-update-rate: 20
  max-favorite-count: 100
  favorite-cancel-rate: 10
  cart-per-user-rate: 10
  cart-max-sku-count: 8
  cart-max-sku-number: 3
  cart-source-type-rates: [60, 20, 10, 10]
  order-user-rate: 30
  order-sku-rate: 50
  order-join-activity: false
  order-use-coupon: false
  order-back-reason-rates: [30, 10, 20, 5, 15, 5, 5]
  get-coupon-user-count: 100
  payment-rate: 70
  payment-type-rates: [30, 60, 10]
  comment-brand-rates: [30, 10, 10, 50]
  http-url: http://minikube:8888/report
  max-device-id: 20
  max-user-id: 50
  max-sku-id: 10
  max-page-duration: 20000
  error-rate: 3
  logs-interval: 100
  sku-detail-source-type-rates: [40, 25, 15, 20]
  user-get-coupon-rate: 75
  max-coupon-id: 3
  search-keywords: [图书, 小米, iphone11, 电视, 口红, PS5, 苹果手机, 小米盒子]
