logging:
  pattern:
    console: \%m\%n
  level:
    root: info

spring:
  main:
    banner-mode: off
  task:
    execution:
      thread-name-prefix: AppLogMocker-
      pool:
        max-size: 100
        core-size: 20
        keep-alive: 180s
        queue-capacity: 5000
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://minikube:3306/demo?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: demo
    password: 123456
  kafka:
    template:
      default-topic: ods-base-log
    producer:
      acks: 0
    bootstrap-servers:
    - minikube:9092
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis-plus:
  global-config:
    db-config:
      field-strategy: not-null

mocker:
  business-date: 2020-12-18
  app-client-concurrence: 10
  collect-type: LOG
  is-clear: false
  user-logon-count: 50
  male-user-rate: 20
  user-info-update-rate: 20
  total-favorite-count: 100
  cancel-favorited-rate: 10
  per-user-in-cart-rate: 10
  max-sku-type-in-cart: 8
  max-sku-number-in-cart: 3
  source-type-of-in-cart-rates: [60, 20, 10, 10]
  per-user-ordered-rate: 30
  per-sku-ordered-rate: 50
  order-join-activity: false
  order-used-coupon: false
  got-coupon-user-rate: 75
  users-count-of-got-coupon: 100
  order-back-rate: 30
  order-back-reason-rates: [30, 10, 20, 5, 15, 5, 5]
  payment-rate: 70
  payment-type-rates: [30, 60, 10]
  comment-grade-rates: [30, 10, 10, 50]
  http-url: http://minikube:8888/report
  max-device-id: 20
  max-user-id: 50
  max-sku-id: 10
  max-page-duration: 20000
  errors-triggered-rate: 3
  max-logs-interval: 1000
  sku-detail-source-type-rates: [40, 25, 15, 20]
  max-coupon-id: 3
  search-keywords: [图书, 小米, iphone11, 电视, 口红, PS5, 苹果手机, 小米盒子]
