###
# Date        : 2019-12-07 19:09:54
# Author      : shy
# Email       : yushuibo@ebupt.com / hengchen2005@gmail.com
# Version     : v1.0
# Description : -
###
# debug: true

spring:
  http:
    encoding:
      # 解决静态资源中文乱码问题
      charset: utf-8
      enabled: true
      force: true
  application:
    name: spring-demos

  # SpringBoot静态资源
  # 默认路径为以下4个目录：
  # 1. classpath:/META-INF/resources/
  # 2. classpath:/resources/
  # 3. classpath:/static/
  # 4. classpath:/public/
  # 也就是说如果想访问静态资源，则需要将静态资源 文件放在这四个路径下面，其中，classpath指的是 resources目录
  # 此处将静态资源路径改为 /resources/templates，默认的配置将会失效
  #
  # 以下通过代码方式修改静态资源默认路径
  #
  # @Configuration
  # public class FileConfig implements WebMvcConfigurer {
  #
  #  @Override
  #  public void addResourceHandlers(ResourceHandlerRegistry registry) {
  #      registry.addResourceHandler("/**").addResourceLocations("classpath:/templates/");
  #  }
  #
  resources:
    static-locations: classpath:/templates/

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30006/demo
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect

# 使用 @Value 获取自定义的配置项
# @Value("${config.name}")
# @Value("${config.age}")
config:
  name: shy
  age: 18

# @Value 同时支持配置项的引用
age: 20
cupSize: E
content: age=${age}, cupSize=${cupSize}


# @ConfigurationProperties(prefix="girl")
# 将配置组转换为 Pojo
girl:
  age: 18
  cupSize: C

# 文件上传
# 不能带协议 file://，否则会找不到文件
file:
  upload:
    path: /Users/shy/Downloads/


