// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package me.shy.netty.netty.rpc.grpc.greetingGen;

/**
 * Protobuf type {@code me.shy.demo.grpc.GreetingResponse}
 */
public  final class GreetingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.shy.demo.grpc.GreetingResponse)
    GreetingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GreetingResponse.newBuilder() to construct.
  private GreetingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GreetingResponse() {
    greetWords_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GreetingResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GreetingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            greetWords_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.shy.netty.netty.rpc.grpc.greetingGen.Greeting.internal_static_me_shy_demo_grpc_GreetingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.shy.netty.netty.rpc.grpc.greetingGen.Greeting.internal_static_me_shy_demo_grpc_GreetingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse.class, me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse.Builder.class);
  }

  public static final int GREETWORDS_FIELD_NUMBER = 1;
  private volatile java.lang.Object greetWords_;
  /**
   * <code>string greetWords = 1;</code>
   * @return The greetWords.
   */
  public java.lang.String getGreetWords() {
    java.lang.Object ref = greetWords_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      greetWords_ = s;
      return s;
    }
  }
  /**
   * <code>string greetWords = 1;</code>
   * @return The bytes for greetWords.
   */
  public com.google.protobuf.ByteString
      getGreetWordsBytes() {
    java.lang.Object ref = greetWords_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      greetWords_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getGreetWordsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, greetWords_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getGreetWordsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, greetWords_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse)) {
      return super.equals(obj);
    }
    me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse other = (me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse) obj;

    if (!getGreetWords()
        .equals(other.getGreetWords())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GREETWORDS_FIELD_NUMBER;
    hash = (53 * hash) + getGreetWords().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.shy.demo.grpc.GreetingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.shy.demo.grpc.GreetingResponse)
      me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.shy.netty.netty.rpc.grpc.greetingGen.Greeting.internal_static_me_shy_demo_grpc_GreetingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.shy.netty.netty.rpc.grpc.greetingGen.Greeting.internal_static_me_shy_demo_grpc_GreetingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse.class, me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse.Builder.class);
    }

    // Construct using me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      greetWords_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.shy.netty.netty.rpc.grpc.greetingGen.Greeting.internal_static_me_shy_demo_grpc_GreetingResponse_descriptor;
    }

    @java.lang.Override
    public me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse getDefaultInstanceForType() {
      return me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse build() {
      me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse buildPartial() {
      me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse result = new me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse(this);
      result.greetWords_ = greetWords_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse) {
        return mergeFrom((me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse other) {
      if (other == me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse.getDefaultInstance()) return this;
      if (!other.getGreetWords().isEmpty()) {
        greetWords_ = other.greetWords_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object greetWords_ = "";
    /**
     * <code>string greetWords = 1;</code>
     * @return The greetWords.
     */
    public java.lang.String getGreetWords() {
      java.lang.Object ref = greetWords_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        greetWords_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string greetWords = 1;</code>
     * @return The bytes for greetWords.
     */
    public com.google.protobuf.ByteString
        getGreetWordsBytes() {
      java.lang.Object ref = greetWords_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        greetWords_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string greetWords = 1;</code>
     * @param value The greetWords to set.
     * @return This builder for chaining.
     */
    public Builder setGreetWords(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      greetWords_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string greetWords = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGreetWords() {

      greetWords_ = getDefaultInstance().getGreetWords();
      onChanged();
      return this;
    }
    /**
     * <code>string greetWords = 1;</code>
     * @param value The bytes for greetWords to set.
     * @return This builder for chaining.
     */
    public Builder setGreetWordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      greetWords_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.shy.demo.grpc.GreetingResponse)
  }

  // @@protoc_insertion_point(class_scope:me.shy.demo.grpc.GreetingResponse)
  private static final me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse();
  }

  public static me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GreetingResponse>
      PARSER = new com.google.protobuf.AbstractParser<GreetingResponse>() {
    @java.lang.Override
    public GreetingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GreetingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GreetingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GreetingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.shy.netty.netty.rpc.grpc.greetingGen.GreetingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

